stages:
  - build
  - deploy

variables:
  REGISTRY_USER: $CI_REGISTRY_USER
  REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  DOCKER_REGISTRY_IMAGE: 4anchor/testapp
  DOCKER_REGISTRY_TAG: $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_TAG
  CHART_PATH: ./

build:
  stage: build
  script:
    - docker build -t $DOCKER_REGISTRY_TAG ./app
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" docker.io
    - docker push $DOCKER_REGISTRY_TAG
  only:
    - tags

deploy:
  stage: deploy
  script:
    - helm upgrade --install myapp $CHART_PATH -n django-app --set app.image.repository=$DOCKER_REGISTRY_IMAGE,image.tag=$CI_COMMIT_TAG
  only:
    - tags
