apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "testapp.fullname" . }}-ingress
spec:
  rules:
    - host: testapp.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
